server:
  port: 10010
spring:
  application:
    name: spring-office-gateway
  cloud:
    nacos:
      server-addr: localhost:8848
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**
        - id: role-service
          uri: lb://role-service
          predicates:
            - Path=/role/**
        - id: book-service
          uri: lb://book-service
          predicates:
            - Path=/book/**
        - id: check-service
          uri: lb://check-service
          predicates:
            - Path=/check/**
        - id: department-service
          uri: lb://department-service
          predicates:
            - Path=/department/**
        - id: meeting-service
          uri: lb://meeting-service
          predicates:
            - Path=/meeting/**
        - id: message-service
          uri: lb://message-service
          predicates:
            - Path=/message/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:8080"
              - "http://localhost:5173"
            allowedMethods:
              - "GET"
              - "POST"
              - "PUT"
              - "DELETE"
            allowedHeaders: "*"
            allowCredentials: true
            maxAge: 36000
