server:
  port: 8085

spring:
  application:
    name: message-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/g435office?useSSL=false
    username: root
    password: root
  cloud:
    nacos:
      server-addr: localhost:8848
      discovery:
        cluster-name: HZ
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

mybatis-plus:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.example.message.entity
