server:
  port: 8083

spring:
  application:
    name: role-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/g435office?useSSL=false
    username: root
    password: root
  cloud:
    nacos:
      server-addr: localhost:8848
      discovery:
        cluster-name: HZ

mybatis-plus:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.example.role.entity